<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_archivo  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["BeforeShowAdd"]=true;

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		$userData = Security::currentUserData();
$values['usuario_creacion']=$userData["id"];
$values['id_tipo_archivo']=$_SESSION['_enviar_archivo_id_tipo_archivo'];
$values['postulacion_id']=$_SESSION['_enviar_archivo_id_postulacion'];
$values['person_id']=$_SESSION['_enviar_archivo_id_persona'];

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		if(isset($_SESSION['_enviar_archivo_id_tipo_archivo'])){

}else{
	$_SESSION['_enviar_archivo_id_tipo_archivo']=1;
}

if(isset($_SESSION['_enviar_archivo_id_postulacion'])){

}else{
	$_SESSION['_enviar_archivo_id_postulacion']=0;
}

;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		//insertar archivo relacionado a persona


unset($_SESSION['_enviar_archivo_id_tipo_archivo']);
unset($_SESSION['_enviar_archivo_id_persona']);
unset($_SESSION['_enviar_archivo_id_postulacion']);


  echo '<script type="text/javascript">
        if(window.opener) {
            window.opener.location.reload(); // Recarga la página padre si es necesario
        }
        window.close(); // Cierra la ventana
    </script>';
    exit(); // Termina la ejecución para que no siga mostrando el formulario



print_r("Guardado: cerrar ventana.");
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
