<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bolsa_users_popup  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;

		$this->events["BeforeShowEdit"]=true;


		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		//Ocultar elementos que es necesario que sean visibles en el listado.
//$pageObject->hideItem("grid_view");
$pageObject->hideItem("add", $recordId);					//oculta el boton "Añadir Nuevo"
$pageObject->hideItem("print_panel", $recordId);	//oculta el icono de impresora
$pageObject->hideItem("breadcrumb", $recordId);		//oculta el breadcrumb
$pageObject->hideItem("list_options", $recordId);	//oculta la lista de opciones del menu
$pageObject->hideItem("page_size", $recordId);		//oculta la cantidad de registros por pagina
$pageObject->hideItem("grid_field1", $recordId);	//Oculta el campo id_vacancias
$pageObject->hideItem("grid_field2", $recordId);	//Oculta el campo id_persona


//print_r($_SESSION);
//$_SESSION["UserData"]["id"],
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->hideItem("integrated_edit_field19", $recordId); //oculta el campo id
$pageObject->hideItem("integrated_edit_field3", $recordId); //oculta el campo groupid
$pageObject->hideItem("integrated_edit_field4", $recordId); //oculta el campo active
$pageObject->hideItem("integrated_edit_field5", $recordId); //oculta el campo reset_token
$pageObject->hideItem("integrated_edit_field6", $recordId); //oculta el campo reset_date
$pageObject->hideItem("integrated_edit_field7", $recordId); //oculta el campo fecha_alta
$pageObject->hideItem("integrated_edit_field8", $recordId); //oculta el campo llave
$pageObject->hideItem("integrated_edit_field9", $recordId);  //oculta el campo estado_llave
$pageObject->hideItem("integrated_edit_field10", $recordId); //oculta el campo senadis
$pageObject->hideItem("integrated_edit_field11", $recordId); //oculta el campo trabajo_antes
$pageObject->hideItem("integrated_edit_field12", $recordId); //oculta el campo userpic
$pageObject->hideItem("integrated_edit_field13", $recordId); //oculta el campo personaid
$pageObject->hideItem("integrated_edit_field15", $recordId); //oculta el campo username
$pageObject->hideItem("integrated_edit_field16", $recordId);  //oculta el campo hash_generado
$pageObject->hideItem("integrated_edit_field17", $recordId); //oculta el campo adjunto_foto_perfil
$pageObject->hideItem("integrated_edit_field", $recordId); //oculta el campo nro_documento
$pageObject->hideItem("integrated_edit_field14", $recordId); //oculta el campo fullname

$pageObject->hideItem("edit_save", $recordId); //oculta el boton original o por defecto de "Guardar" para que se utilice el boton personalizado para guardar cambios

$pageObject->hideItem("edit_message", $recordId); //el mensaje de cambio de registros
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		
// Place event code here.
// Use "Add Action" button to add code snippets.


;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
