<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_postulacion_preseleccionado  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		// ──────────────────────────────────────────────────────────────────────────
// OCULTAR CAMPOS QUE NO DEBEN SER VISIBLES EN EL LISTADO
// ──────────────────────────────────────────────────────────────────────────
$pageObject->hideItem("grid_field5", $recordId); //Oculta el campo id_postulacion
$pageObject->hideItem("grid_field3", $recordId); //Oculta el campo id_vacancias


// ──────────────────────────────────────────────────────────────────────────
// VALIDACIÓN DE ESTADO PARA CAMBIO MASIVO
// ──────────────────────────────────────────────────────────────────────────

/*
 * Para permitir el cambio masivo de estados, la vacancia no debe estar en estado "Cerrada"
 * ni "Convocatoria Cerrada". Se define una lista de estados donde se restringe esta acción.
 */

// Obtener el registro principal de la página
$data = $pageObject ->getMasterRecord();

// Consulta para obtener el estado actual de la vacancia
$sql = "SELECT id_estado_vacancia 
					FROM bolsa_empleo.vacancia 
					WHERE id_vacancias = " . $data["id_vacancias"];
$result = CustomQuery($sql);
$data_result = db_fetch_array($result);


// ──────────────────────────────────────────────────────────────────────────
// LISTA DE ESTADOS DONDE SE DEBEN OCULTAR LOS ELEMENTOS
// ──────────────────────────────────────────────────────────────────────────
$estadosOcultar = [1, 2, 4, 5, 6, 7]; // Estados en los que se deshabilita el cambio de estado masivo


// Verificar si la vacancia está en un estado restringido
if (in_array($data_result["id_estado_vacancia"], $estadosOcultar)) {
	// Ocultar botones y textos relacionados con el cambio de estado masivo
	$pageObject->hideItem("button_cambiar_estado_preseleccionado", $recordId);
	$pageObject->hideItem("text_cambiar_estado_preseleccionado", $recordId);
} else {
	// Mostrar los elementos si la vacancia permite el cambio masivo de estado
	// Observacion: Solo se puede realizar un cambio de estado cuando el estado de la vacancia esta en: Evaluación(id=3)
	$pageObject->showItem("button_cambiar_estado_preseleccionado", $recordId);
	$pageObject->showItem("text_cambiar_estado_preseleccionado", $recordId);
}

//print_r($_SESSION);

;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
