<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_postulacion_seleccionado  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;

		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		
// ──────────────────────────────────────────────────────────────────────────
// OCULTAR CAMPOS QUE NO DEBEN SER VISIBLES EN EL LISTADO
// ──────────────────────────────────────────────────────────────────────────
//$pageObject->hideItem("grid_field1", $recordId);	//Oculta el campo "id_vacancia"
$pageObject->hideItem("grid_field2", $recordId);	//Oculta el campo "id_vacancias"
$pageObject->hideItem("grid_field", $recordId);		//Oculta el campo "id_postulacion"


// ──────────────────────────────────────────────────────────────────────────
// VALIDACIÓN DE ESTADO PARA CAMBIO MASIVO
// ──────────────────────────────────────────────────────────────────────────

/*
 * Para permitir el cambio masivo de estados, la vacancia no debe estar en estado "Cerrada"
 * ni "Convocatoria Cerrada". Se define una lista de estados donde se restringe esta acción.
 */

// Obtener el registro principal de la página
$data = $pageObject ->getMasterRecord();

// Consulta para obtener el estado actual de la vacancia
$sql = "SELECT id_estado_vacancia 
					FROM bolsa_empleo.vacancia 
					WHERE id_vacancias = " . $data["id_vacancias"];
$result = CustomQuery($sql);
$data_result = db_fetch_array($result);


// ──────────────────────────────────────────────────────────────────────────
// LISTA DE ESTADOS DONDE SE DEBEN OCULTAR LOS ELEMENTOS
// ──────────────────────────────────────────────────────────────────────────
$estadosOcultar = [1, 2, 4, 5, 6, 7, 10]; // Estados en los que se deshabilita el cambio de estado masivo


// Verificar si la vacancia está en un estado restringido
if (in_array($data_result["id_estado_vacancia"], $estadosOcultar)) {
		// Ocultar botones y textos relacionados con el cambio de estado masivo
    $pageObject->hideItem("button_cambiar_estado_seleccionado", $recordId);
    $pageObject->hideItem("text_cambiar_estado_seleccionado", $recordId);
} else {
		// Mostrar los elementos si la vacancia permite el cambio masivo de estado
    $pageObject->showItem("button_cambiar_estado_seleccionado", $recordId);
    $pageObject->showItem("text_cambiar_estado_seleccionado", $recordId);
}



//Utilizado en el evento 'Client Before' del boton 'Cambiar estado', para poder obtener el 'id_vacancias'.
$pageObject->setProxyValue("master",$pageObject->getMasterRecord());

;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if ($data['es_programa']==true){
	if(empty($data['test_psicotecnico'])||empty($data['evaluacion'])){
	$pageObject->hideItem("grid_checkbox", $recordId);
	}
}
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
