<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_postulacion_preseleccionado  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		//Ocultar campos que no van a ser visibles en el listado.
$pageObject->hideItem("grid_field5", $recordId); //Oculta el campo id_postulacion
$pageObject->hideItem("grid_field3", $recordId); //Oculta el campo id_vacancias

/*
 * Para realizar un cambio de estados masivo la condicion es que una vacancia no este con el estado
 * "Cerrada" o "Convocatoria Cerrada".
*/
$data = $pageObject ->getMasterRecord();

$sql = "SELECT id_estado_vacancia FROM bolsa_empleo.vacancia WHERE id_vacancias = " . $data["id_vacancias"];
$result = CustomQuery($sql);
$data_result = db_fetch_array($result);

// Definir los estados en los que se deben ocultar los elementos
//$estadosOcultar = [5, 6];
$estadosOcultar = [1, 2, 4, 5, 6, 7];

if (in_array($data_result["id_estado_vacancia"], $estadosOcultar)) {
    // Ocultar los elementos
    $pageObject->hideItem("button_cambiar_estado_preseleccionado", $recordId);
    $pageObject->hideItem("text_cambiar_estado_preseleccionado", $recordId);
} else {
    // Mostrar los elementos
    $pageObject->showItem("button_cambiar_estado_preseleccionado", $recordId);
    $pageObject->showItem("text_cambiar_estado_preseleccionado", $recordId);
}
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
