<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_postulacion  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		//$pageObject->hideItem("grid_field2", $recordId);

if ($data["sexo"] == 'M') {  
	$data["sexo"] = "Masculino";
} elseif ($data["sexo"] == 'm') {  
	$data["sexo"] = "Masculino";
} elseif ($data["sexo"] == 'F') {  
	$data["sexo"] = "Femenino";
} elseif ($data["sexo"] == 'f') {  
	$data["sexo"] = "Femenino";
} else {  
	$data["sexo"] = "Indefinidido";
}

;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		//Ocultar items que no van a ser utilizados visualmente en el formulario.
$pageObject->hideItem("grid_field2"); //Oculta el campo hash


$pageObject->hideItem("print_panel"); //Oculta el icono de la impresora

;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
